package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;
import io.flutter.Log;

import io.flutter.embedding.engine.FlutterEngine;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  private static final String TAG = "GeneratedPluginRegistrant";
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    try {
      flutterEngine.getPlugins().add(new io.flutter.plugins.flutter_plugin_android_lifecycle.FlutterAndroidLifecyclePlugin());
    } catch(Exception e) {
      Log.e(TAG, "Error registering plugin flutter_plugin_android_lifecycle, io.flutter.plugins.flutter_plugin_android_lifecycle.FlutterAndroidLifecyclePlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.huawei.hms.flutter.ar.AREnginePlugin());
    } catch(Exception e) {
      Log.e(TAG, "Error registering plugin huawei_ar, com.huawei.hms.flutter.ar.AREnginePlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.huawei.hms.flutter.hmsavailability.HuaweiAvailabilityPlugin());
    } catch(Exception e) {
      Log.e(TAG, "Error registering plugin huawei_hmsavailability, com.huawei.hms.flutter.hmsavailability.HuaweiAvailabilityPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.huawei.hms.flutter.location.LocationPlugin());
    } catch(Exception e) {
      Log.e(TAG, "Error registering plugin huawei_location, com.huawei.hms.flutter.location.LocationPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.huawei.hms.flutter.map.HmsMap());
    } catch(Exception e) {
      Log.e(TAG, "Error registering plugin huawei_map, com.huawei.hms.flutter.map.HmsMap", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.huawei.hms.flutter.ml.HuaweiMlPlugin());
    } catch(Exception e) {
      Log.e(TAG, "Error registering plugin huawei_ml, com.huawei.hms.flutter.ml.HuaweiMlPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.huawei.hms.flutter.push.PushPlugin());
    } catch(Exception e) {
      Log.e(TAG, "Error registering plugin huawei_push, com.huawei.hms.flutter.push.PushPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.huawei.hms.flutter.site.SitePlugin());
    } catch(Exception e) {
      Log.e(TAG, "Error registering plugin huawei_site, com.huawei.hms.flutter.site.SitePlugin", e);
    }
  }
}
